"""add table Email

Revision ID: 975901e10c9d
Revises: 8099c86979ad
Create Date: 2020-02-01 17:55:43.689786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975901e10c9d'
down_revision = '8099c86979ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_value'), 'email', ['value'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_value'), table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###
