"""add test

Revision ID: b757e3cc4118
Revises: 975901e10c9d
Create Date: 2020-02-06 17:09:14.783658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b757e3cc4118'
down_revision = '975901e10c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=2048), nullable=True),
    sa.Column('answer1', sa.String(length=2048), nullable=True),
    sa.Column('answer2', sa.String(length=2048), nullable=True),
    sa.Column('answer3', sa.String(length=2048), nullable=True),
    sa.Column('answer4', sa.String(length=2048), nullable=True),
    sa.Column('correct_answer', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('material', sa.Column('tests', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'tests')
    op.drop_table('test')
    # ### end Alembic commands ###
