"""add position and organization for User

Revision ID: cb42141f6e1b
Revises: 61f38354b7d5
Create Date: 2020-02-19 00:02:41.035753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb42141f6e1b'
down_revision = '61f38354b7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('position', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'position')
    op.drop_column('user', 'organization')
    # ### end Alembic commands ###
